name: ci

on:
  push:
    branches:
      - '*'
    paths:
      - 'charts/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        shell: bash
        run: |
          ## For all files that were changed, find the root directory of the chart and lint it
          for f in $(git diff --name-only --diff-filter=ACMRTUXB HEAD~1); do
            dir=$(dirname "$f")
            while [ "$dir" != "." ]; do
              if [ -f "$dir/Chart.yaml" ]; then
                helm lint "$dir"
                break
              fi
              dir=$(dirname "$dir")
            done
          done