name: publish

on:
  push:
    branches:
      - 'monorepo'

jobs:
  helm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::489099442433:role/GitHubECRActionRole
          role-duration-seconds: 3600

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the chart(s) to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        shell: bash
        run: |
          ## For any Chart.yaml files that were changed, find the root directory of the chart, find the chart version from Chart.yaml, package it and push it to Amazon ECR using helm
          for f in $(git diff --name-only --diff-filter=ACMRTUXB HEAD~1 HEAD); do
            dir=$(dirname "$f")
            while [ "$dir" != "." ]; do
              if [ -f "$dir/Chart.yaml" ]; then
                version=$(helm inspect chart "$dir" | grep version | awk '{print $2}')
                helm package "$dir" --version "$version"
                helm push "$(basename $($dir))-$version.tgz" "oci://${{ steps.login-ecr.outputs.registry }}"
                break
              fi
              dir=$(dirname "$dir")
            done
          done
          
